### ISSUE TITLE
Cloudant Version Issue

### ISSUE THREAD

**Issue by TCUCheech15** [Watson-Personal-Assistant/skill-sdk-nodejs#7]
The line "cloudant": "^1.7.1" in the package.json file creates a build issue when trying to deploy to bluemix.  Bluemix is unable to find the newest version of cloudant it is trying to create.
![screen shot 2018-02-14 at 11 14 14 am](https://user-images.githubusercontent.com/4122319/36230558-653c4532-11a0-11e8-9c84-fc3845130660.png)

**Comment by deanhaber** [comment]
Hey @TCUCheech15 

For an unknown reason (at least for me) most cloudant npm version stopped working...
For another unknown reason we are dependent on "cloudant" npm...
So I just removed it. 

Please "npm update" this SDK and verify that it is working so we can close this issue.
Thanks!
